name: CI_test
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21.0.2
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
      - run: mvn -v
      - name:  Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Compile
        run: mvn -X compile
      - name: Test
        run: mvn -X test
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/surefire-reports/index.html
