name: test
on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: s4u/setup-maven-action@3.9.8
      - run: mvn install
      - name: generate report
        run: mvn test
      - uses: pavi2410/html-preview-action@v2
        with:
            html_file: 'maven_selenium\target\surefire-reports\index.html'