name: CI_test
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name:  Install Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Build
        run: mvn build
      - name: Test
        run: mvn test
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/surefire-reports/index.html
